HISAXCTRL_VERSION = $(ISDNUTILS_VERSION)
HISAXCTRL_SOURCE = $(ISDNUTILS_SOURCE)
HISAXCTRL_PATCH = $(ISDNUTILS_PATCH)
HISAXCTRL_SITE = $(ISDNUTILS_SITE)
HISAXCTRL_SUBDIR = hisax

HISAXCTRL_LICENSE = GPLv2+
HISAXCTRL_LICENSE_FILES = gpl-2.0.txt

HISAXCTRL_CONF_ENV = $(ISDNUTILS_CONF_ENV)
HISAXCTRL_CONF_OPTS = --with-hisax=y
HISAXCTRL_MAKE_OPTS = CFLAGS="$(TARGET_CFLAGS)"

HISAXCTRL_PRE_CONFIGURE_HOOKS += ISDNUTILS_PREPARE_CONFIG

define HISAXCTRL_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/$(HISAXCTRL_SUBDIR)/hisaxctrl $(TARGET_DIR)/sbin/hisaxctrl
endef

$(eval $(call autotools-package))
