LIBCAPI20_VERSION = $(ISDNUTILS_VERSION)
LIBCAPI20_SOURCE = $(ISDNUTILS_SOURCE)
LIBCAPI20_PATCH = $(ISDNUTILS_PATCH)
LIBCAPI20_SITE = $(ISDNUTILS_SITE)
LIBCAPI20_SUBDIR = capi20

LIBCAPI20_LICENSE = LGPLv2.1, GPLv2+
LIBCAPI20_LICENSE_FILES = capi20/COPYING.LIB \
                          capi20/COPYING

LIBCAPI20_INSTALL_STAGING = YES
LIBCAPI20_AUTORECONF = YES
LIBCAPI20_CONF_ENV = $(ISDNUTILS_CONF_ENV)

LIBCAPI20_PRE_CONFIGURE_HOOKS += ISDNUTILS_PREPARE_CONFIG

$(eval $(call autotools-package))
