#!/bin/sh

git diff --name-status fli4l-r60808-orig..fli4l-r60808-becto -- \
	':(exclude,top)src/packages/accounting' \
	':(exclude,top)src/packages/advanced_networking' \
	':(exclude,top)src/packages/c3surf' \
	':(exclude,top)src/packages/cert' \
	':(exclude,top)src/packages/checkmk' \
	':(exclude,top)src/packages/cifs' \
	':(exclude,top)src/packages/cpanel' \
	':(exclude,top)src/packages/cpmvrmlog' \
	':(exclude,top)src/packages/dslmodem' \
	':(exclude,top)src/packages/dsltool' \
	':(exclude,top)src/packages/dyndns' \
	':(exclude,top)src/packages/faxrcv' \
	':(exclude,top)src/packages/firmware' \
	':(exclude,top)src/packages/freifunk' \
	':(exclude,top)src/packages/fritzbox' \
	':(exclude,top)src/packages/imonc_unix' \
	':(exclude,top)src/packages/imonc_windows' \
	':(exclude,top)src/packages/ipsec-tools' \
	':(exclude,top)src/packages/ipv6' \
	':(exclude,top)src/packages/isdn' \
	':(exclude,top)src/packages/joe' \
	':(exclude,top)src/packages/kernel_5_4' \
	':(exclude,top)src/packages/knxeib' \
	':(exclude,top)src/packages/lcd' \
	':(exclude,top)src/packages/lcd4linux' \
	':(exclude,top)src/packages/metalog' \
	':(exclude,top)src/packages/modem' \
	':(exclude,top)src/packages/mtgcapri' \
	':(exclude,top)src/packages/muninnode' \
	':(exclude,top)src/packages/ntp' \
	':(exclude,top)src/packages/oidentd' \
	':(exclude,top)src/packages/ow' \
	':(exclude,top)src/packages/pcmcia' \
	':(exclude,top)src/packages/phonebook' \
	':(exclude,top)src/packages/proxy' \
	':(exclude,top)src/packages/qos' \
	':(exclude,top)src/packages/register' \
	':(exclude,top)src/packages/rsync' \
	':(exclude,top)src/packages/samba_lpd' \
	':(exclude,top)src/packages/squid' \
	':(exclude,top)src/packages/template' \
	':(exclude,top)src/packages/ucarp' \
	':(exclude,top)src/packages/ulogd' \
	':(exclude,top)src/packages/umts' \
	':(exclude,top)src/packages/vbox' \
	':(exclude,top)src/packages/virt' \
	':(exclude,top)src/packages/vpn' \
	':(exclude,top)src/packages/wlan' \
	':(exclude,top)src/packages/yaps' \
	    > ../_nanoc/layouts/partials/diff_r60808-orig+r60808-becto.txt
