CAPIINFO_VERSION = $(ISDNUTILS_VERSION)
CAPIINFO_SOURCE = $(ISDNUTILS_SOURCE)
CAPIINFO_PATCH = $(ISDNUTILS_PATCH)
CAPIINFO_SITE = $(ISDNUTILS_SITE)
CAPIINFO_SUBDIR = capiinfo

CAPIINFO_LICENSE = GPLv2+
CAPIINFO_LICENSE_FILES = gpl-2.0.txt

CAPIINFO_DEPENDENCIES = libcapi20
CAPIINFO_AUTORECONF = YES
CAPIINFO_CONF_ENV = $(ISDNUTILS_CONF_ENV)
CAPIINFO_MAKE_OPTS = CFLAGS="$(TARGET_CFLAGS)"

CAPIINFO_PRE_CONFIGURE_HOOKS += ISDNUTILS_PREPARE_CONFIG

define CAPIINFO_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/$(CAPIINFO_SUBDIR)/capiinfo $(TARGET_DIR)/usr/bin/capiinfo
endef

$(eval $(call autotools-package))
