PPPDCAPIPLUGIN_VERSION = $(ISDNUTILS_VERSION)
PPPDCAPIPLUGIN_SOURCE = $(ISDNUTILS_SOURCE)
PPPDCAPIPLUGIN_PATCH = $(ISDNUTILS_PATCH)
PPPDCAPIPLUGIN_SITE = $(ISDNUTILS_SITE)
PPPDCAPIPLUGIN_SUBDIR = pppdcapiplugin

PPPDCAPIPLUGIN_LICENSE = GPLv2+
PPPDCAPIPLUGIN_LICENSE_FILES = gpl-2.0.txt

PPPDCAPIPLUGIN_DEPENDENCIES = libcapi20 pppd
PPPDCAPIPLUGIN_CONF_ENV = $(ISDNUTILS_CONF_ENV)

PPPDCAPIPLUGIN_PRE_CONFIGURE_HOOKS += ISDNUTILS_PREPARE_CONFIG

define PPPDCAPIPLUGIN_BUILD_CMDS
	+$(MAKE) CC=$(TARGET_CC) CCFLAGS="$(TARGET_CFLAGS)" LDFLAGS="$(TARGET_LDFLAGS)" \
		PPPINC=$(STAGING_DIR)/usr/include/pppd \
		-C $(@D)/$(PPPDCAPIPLUGIN_SUBDIR)
endef

define PPPDCAPIPLUGIN_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/$(PPPDCAPIPLUGIN_SUBDIR)/ppp-$(PPPD_VERSION)/capiplugin.so $(TARGET_DIR)/usr/lib/pppd/$(PPPD_VERSION)/capiplugin.so
	$(INSTALL) -D $(@D)/$(PPPDCAPIPLUGIN_SUBDIR)/ppp-$(PPPD_VERSION)/userpass.so $(TARGET_DIR)/usr/lib/pppd/$(PPPD_VERSION)/userpass.so
endef

$(eval $(call generic-package))
