CAPIFAX_VERSION = $(ISDNUTILS_VERSION)
CAPIFAX_SOURCE = $(ISDNUTILS_SOURCE)
CAPIFAX_PATCH = $(ISDNUTILS_PATCH)
CAPIFAX_SITE = $(ISDNUTILS_SITE)
CAPIFAX_SUBDIR = capifax

CAPIFAX_LICENSE = GPLv2+
CAPIFAX_LICENSE_FILES = gpl-2.0.txt

CAPIFAX_DEPENDENCIES = libcapi20
CAPIFAX_AUTORECONF = YES
CAPIFAX_CONF_ENV = $(ISDNUTILS_CONF_ENV) ac_cv_file____capi20_capi20_h=yes
CAPIFAX_MAKE_OPTS = CFLAGS="$(TARGET_CFLAGS)"

CAPIFAX_PRE_CONFIGURE_HOOKS += ISDNUTILS_PREPARE_CONFIG

define CAPIFAX_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/$(CAPIFAX_SUBDIR)/capifax $(TARGET_DIR)/usr/bin/capifax
	$(INSTALL) -D $(@D)/$(CAPIFAX_SUBDIR)/capifaxrcvd $(TARGET_DIR)/usr/bin/capifaxrcvd
endef

$(eval $(call autotools-package))
