DIVERTCTRL_VERSION = $(ISDNUTILS_VERSION)
DIVERTCTRL_SOURCE = $(ISDNUTILS_SOURCE)
DIVERTCTRL_PATCH = $(ISDNUTILS_PATCH)
DIVERTCTRL_SITE = $(ISDNUTILS_SITE)
DIVERTCTRL_SUBDIR = divertctrl

DIVERTCTRL_LICENSE = GPLv2+
DIVERTCTRL_LICENSE_FILES = gpl-2.0.txt

DIVERTCTRL_CONF_ENV = $(ISDNUTILS_CONF_ENV)
DIVERTCTRL_MAKE_OPTS = CFLAGS="$(TARGET_CFLAGS)"

DIVERTCTRL_PRE_CONFIGURE_HOOKS += ISDNUTILS_PREPARE_CONFIG

define DIVERTCTRL_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/$(DIVERTCTRL_SUBDIR)/divertctrl $(TARGET_DIR)/sbin/divertctrl
endef

$(eval $(call autotools-package))
