ACTCTRL_VERSION = $(ISDNUTILS_VERSION)
ACTCTRL_SOURCE = $(ISDNUTILS_SOURCE)
ACTCTRL_PATCH = $(ISDNUTILS_PATCH)
ACTCTRL_SITE = $(ISDNUTILS_SITE)
ACTCTRL_SUBDIR = act2000

ACTCTRL_LICENSE = GPLv2+
ACTCTRL_LICENSE_FILES = gpl-2.0.txt

ACTCTRL_CONF_ENV = $(ISDNUTILS_CONF_ENV)
ACTCTRL_MAKE_OPTS = CFLAGS="$(TARGET_CFLAGS)"

ACTCTRL_PRE_CONFIGURE_HOOKS += ISDNUTILS_PREPARE_CONFIG

define ACTCTRL_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/$(ACTCTRL_SUBDIR)/actctrl $(TARGET_DIR)/sbin/actctrl
endef

$(eval $(call autotools-package))
