RCAPID_VERSION = $(ISDNUTILS_VERSION)
RCAPID_SOURCE = $(ISDNUTILS_SOURCE)
RCAPID_PATCH = $(ISDNUTILS_PATCH)
RCAPID_SITE = $(ISDNUTILS_SITE)
RCAPID_SUBDIR = rcapid

RCAPID_LICENSE = GPLv2+
RCAPID_LICENSE_FILES = gpl-2.0.txt

RCAPID_DEPENDENCIES = libcapi20
RCAPID_CONF_ENV = $(ISDNUTILS_CONF_ENV)
RCAPID_MAKE_OPTS = CFLAGS="$(TARGET_CFLAGS)"

RCAPID_PRE_CONFIGURE_HOOKS += ISDNUTILS_PREPARE_CONFIG

define RCAPID_TOUCH_MAKEFILE
	touch $(RCAPID_DIR)/$(RCAPID_SUBDIR)/Makefile.in
endef
RCAPID_PRE_CONFIGURE_HOOKS += RCAPID_TOUCH_MAKEFILE

define RCAPID_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/$(RCAPID_SUBDIR)/rcapid $(TARGET_DIR)/sbin/rcapid
endef

$(eval $(call autotools-package))
