IMONTTY_VERSION = $(ISDNUTILS_VERSION)
IMONTTY_SOURCE = $(ISDNUTILS_SOURCE)
IMONTTY_PATCH = $(ISDNUTILS_PATCH)
IMONTTY_SITE = $(ISDNUTILS_SITE)
IMONTTY_SUBDIR = imontty

IMONTTY_LICENSE = GPLv2+
IMONTTY_LICENSE_FILES = gpl-2.0.txt

IMONTTY_PRE_CONFIGURE_HOOKS += ISDNUTILS_PREPARE_CONFIG

define IMONTTY_BUILD_CMDS
	+$(MAKE) CC=$(TARGET_CC) LD=$(TARGET_LD) CCFLAGS="$(TARGET_CFLAGS)" \
		-C $(@D)/$(IMONTTY_SUBDIR)
endef

define IMONTTY_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/$(IMONTTY_SUBDIR)/imontty $(TARGET_DIR)/sbin/imontty
endef

$(eval $(call generic-package))
