#!/bin/sh
# $Id: _lex-cv860a.cgi 51847 2018-03-06 14:55:07Z kristov $
# Do not edit! This file is automaticly generated by rrd-cgi.xsl

. /srv/www/include/cgi-helper
# set_debug=yes

# Security
check_rights "hwsupp" "view"

# get some internal variables
. /var/run/hwsupp.conf

show_html_header "LEX Computech CV860A"

if [ -e /srv/www/include/rrd-common.inc ]
then
    . /srv/www/include/rrd-common.inc
    if [ -e /srv/www/include/rrd-lex-cv860a.inc ]
    then
     . /srv/www/include/rrd-lex-cv860a.inc
    fi
fi
if [ -e /srv/www/include/hwmon-lex-cv860a.inc ]
then
    . /srv/www/include/hwmon-lex-cv860a.inc
fi
if [ -e /srv/www/include/extra-cpufreq.inc ]
then
    . /srv/www/include/extra-cpufreq.inc
fi
if [ -e /srv/www/include/extra-dmidecode.inc ]
then
    . /srv/www/include/extra-dmidecode.inc
fi

: ${FORM_action:=lex_cv860a_temp}
if [ -e /srv/www/include/rrd-common.inc ]
then
    : ${FORM_rrd_graphtime_lex_cv860a_temp:=$rrd_default_graphtime}
    : ${FORM_rrd_graphtime_lex_cv860a_voltage:=$rrd_default_graphtime}
    : ${FORM_rrd_graphtime_lex_cv860a_frequency:=$rrd_default_graphtime}

    eval local rrd_source_time='$FORM_rrd_graphtime_'$rrd_source
    : ${rrd_source_time:=$rrd_default_graphtime}
fi
action_list=""
if [ -e /srv/www/include/rrd-common.inc ]
then
    action_list="$action_list temp voltage frequency"
fi
action_list="$action_list hwmon"
if [ "$hwsupp_cpufreq" = "yes" ]
then
    action_list="$action_list cpufreq"
fi
action_list="$action_list bios"

tab_list=""
for i in ${action_list}
do
    case $i in
        temp)
            label=$(translate_label "${_HWSUPP_TEMP}")
        ;;
        voltage)
            label=$(translate_label "${_HWSUPP_VOLTAGE}")
        ;;
        frequency)
            label=$(translate_label "${_HWSUPP_FREQUENCY}")
        ;;
        hwmon)
            label=$(translate_label "${_HWSUPP_HWMON}")
        ;;
        cpufreq)
            label=$(translate_label "${_HWSUPP_CPUFREQ}")
        ;;
        bios)
            label=$(translate_label "${_HWSUPP_DMI}")
        ;;
    esac
    if [ "$FORM_action" = "lex_cv860a_$i" ]
    then
        tab_list=`echo "$tab_list $label no"`
    else
        tab_list=`echo "$tab_list $label $myname?action=lex_cv860a_$i"`
    fi
done

show_tab_header $tab_list
case $FORM_action in
    lex_cv860a_hwmon)
        hwmon_lex_cv860a
    ;;
    lex_cv860a_cpufreq)
        extra_cpufreq
    ;;
    lex_cv860a_bios)
        extra_dmidecode
    ;;
    *)
        rrd_open_tab_list $FORM_action
        rrd_render_graph $FORM_action
        rrd_close_tab_list
    ;;
esac

show_tab_footer

show_html_footer

# _oOo_
