#!/bin/sh
# $Id: _msi-ms-9803.cgi 51847 2018-03-06 14:55:07Z kristov $
# Do not edit! This file is automaticly generated by rrd-cgi.xsl

. /srv/www/include/cgi-helper
# set_debug=yes

# Security
check_rights "hwsupp" "view"

# get some internal variables
. /var/run/hwsupp.conf

show_html_header "Hardware-Support: MSI MS-9803 (coretemp / w83627dhg)"

if [ -e /srv/www/include/rrd-common.inc ]
then
    . /srv/www/include/rrd-common.inc
    if [ -e /srv/www/include/rrd-msi-ms-9803.inc ]
    then
     . /srv/www/include/rrd-msi-ms-9803.inc
    fi
fi
if [ -e /srv/www/include/hwmon-msi-ms-9803.inc ]
then
    . /srv/www/include/hwmon-msi-ms-9803.inc
fi
if [ -e /srv/www/include/extra-cpufreq.inc ]
then
    . /srv/www/include/extra-cpufreq.inc
fi
if [ -e /srv/www/include/extra-dmidecode.inc ]
then
    . /srv/www/include/extra-dmidecode.inc
fi

: ${FORM_action:=msi_ms_9803_frequency}
if [ -e /srv/www/include/rrd-common.inc ]
then
    : ${FORM_rrd_graphtime_msi_ms_9803_frequency:=$rrd_default_graphtime}
    : ${FORM_rrd_graphtime_msi_ms_9803_coretemp:=$rrd_default_graphtime}
    : ${FORM_rrd_graphtime_msi_ms_9803_temp:=$rrd_default_graphtime}
    : ${FORM_rrd_graphtime_msi_ms_9803_fan:=$rrd_default_graphtime}
    : ${FORM_rrd_graphtime_msi_ms_9803_voltage:=$rrd_default_graphtime}

    eval local rrd_source_time='$FORM_rrd_graphtime_'$rrd_source
    : ${rrd_source_time:=$rrd_default_graphtime}
fi
action_list=""
if [ -e /srv/www/include/rrd-common.inc ]
then
    action_list="$action_list frequency coretemp temp fan voltage"
fi
action_list="$action_list hwmon"
if [ "$hwsupp_cpufreq" = "yes" ]
then
    action_list="$action_list cpufreq"
fi
action_list="$action_list bios"

tab_list=""
for i in ${action_list}
do
    case $i in
        frequency)
            label=$(translate_label "${_HWSUPP_FREQUENCY}")
        ;;
        coretemp)
            label=$(translate_label "Core-${_HWSUPP_TEMP}")
        ;;
        temp)
            label=$(translate_label "MB-${_HWSUPP_TEMP}")
        ;;
        fan)
            label=$(translate_label "MB-${_HWSUPP_FANSPEED}")
        ;;
        voltage)
            label=$(translate_label "MB-${_HWSUPP_VOLTAGE}")
        ;;
        hwmon)
            label=$(translate_label "${_HWSUPP_HWMON}")
        ;;
        cpufreq)
            label=$(translate_label "${_HWSUPP_CPUFREQ}")
        ;;
        bios)
            label=$(translate_label "${_HWSUPP_DMI}")
        ;;
    esac
    if [ "$FORM_action" = "msi_ms_9803_$i" ]
    then
        tab_list=`echo "$tab_list $label no"`
    else
        tab_list=`echo "$tab_list $label $myname?action=msi_ms_9803_$i"`
    fi
done

show_tab_header $tab_list
case $FORM_action in
    msi_ms_9803_hwmon)
        hwmon_msi_ms_9803
    ;;
    msi_ms_9803_cpufreq)
        extra_cpufreq
    ;;
    msi_ms_9803_bios)
        extra_dmidecode
    ;;
    *)
        rrd_open_tab_list $FORM_action
        rrd_render_graph $FORM_action
        rrd_close_tab_list
    ;;
esac

show_tab_footer

show_html_footer

# _oOo_
