#!/bin/sh
# $Id: _pcengines-alix.cgi 51847 2018-03-06 14:55:07Z kristov $
# Do not edit! This file is automaticly generated by rrd-cgi.xsl

. /srv/www/include/cgi-helper
# set_debug=yes

# Security
check_rights "hwsupp" "view"

# get some internal variables
. /var/run/hwsupp.conf

show_html_header "PC Engines ALIX"

if [ -e /srv/www/include/rrd-common.inc ]
then
    . /srv/www/include/rrd-common.inc
    if [ -e /srv/www/include/rrd-pcengines-alix.inc ]
    then
     . /srv/www/include/rrd-pcengines-alix.inc
    fi
fi
if [ -e /srv/www/include/hwmon-pcengines-alix.inc ]
then
    . /srv/www/include/hwmon-pcengines-alix.inc
fi
if [ -e /srv/www/include/extra-dmidecode.inc ]
then
    . /srv/www/include/extra-dmidecode.inc
fi
if [ -e /srv/www/include/extra-pcengines-alix.inc ]
then
    . /srv/www/include/extra-pcengines-alix.inc
fi

: ${FORM_action:=pcengines_alix_temp}
if [ -e /srv/www/include/rrd-common.inc ]
then
    : ${FORM_rrd_graphtime_pcengines_alix_temp:=$rrd_default_graphtime}

    eval local rrd_source_time='$FORM_rrd_graphtime_'$rrd_source
    : ${rrd_source_time:=$rrd_default_graphtime}
fi
action_list=""
if [ -e /srv/www/include/rrd-common.inc ]
then
    action_list="$action_list temp"
fi
action_list="$action_list hwmon"
action_list="$action_list bios"
action_list="$action_list alix"

tab_list=""
for i in ${action_list}
do
    case $i in
        temp)
            label=$(translate_label "${_HWSUPP_TEMP}")
        ;;
        hwmon)
            label=$(translate_label "${_HWSUPP_HWMON}")
        ;;
        bios)
            label=$(translate_label "${_HWSUPP_DMI}")
        ;;
        alix)
            label=$(translate_label "alix")
        ;;
    esac
    if [ "$FORM_action" = "pcengines_alix_$i" ]
    then
        tab_list=`echo "$tab_list $label no"`
    else
        tab_list=`echo "$tab_list $label $myname?action=pcengines_alix_$i"`
    fi
done

show_tab_header $tab_list
case $FORM_action in
    pcengines_alix_hwmon)
        hwmon_pcengines_alix
    ;;
    pcengines_alix_bios)
        extra_dmidecode
    ;;
    pcengines_alix_alix)
        extra_pcengines_alix
    ;;
    *)
        rrd_open_tab_list $FORM_action
        rrd_render_graph $FORM_action
        rrd_close_tab_list
    ;;
esac

show_tab_footer

show_html_footer

# _oOo_
