#!/bin/sh
# $Id: rrd-cgi.xsl 32500 2014-08-27 07:03:37Z kristov $
# Do not edit! This file is automaticly generated by rrd-cgi.xsl

. /srv/www/include/cgi-helper
# set_debug=yes

# Security
check_rights "hwsupp" "view"

# get some internal variables
. /var/run/hwsupp.conf

show_html_header "Raspberry Pi"

if [ -e /srv/www/include/rrd-common.inc ]
then
    . /srv/www/include/rrd-common.inc
    if [ -e /srv/www/include/rrd-raspberry-pi.inc ]
    then
     . /srv/www/include/rrd-raspberry-pi.inc
    fi
fi
if [ -e /srv/www/include/hwmon-raspberry-pi.inc ]
then
    . /srv/www/include/hwmon-raspberry-pi.inc
fi

: ${FORM_action:=raspberry_pi_temp}
if [ -e /srv/www/include/rrd-common.inc ]
then
    : ${FORM_rrd_graphtime_raspberry_pi_temp:=$rrd_default_graphtime}

    eval local rrd_source_time='$FORM_rrd_graphtime_'$rrd_source
    : ${rrd_source_time:=$rrd_default_graphtime}
fi
action_list=""
if [ -e /srv/www/include/rrd-common.inc ]
then
    action_list="$action_list temp"
fi
action_list="$action_list hwmon"

tab_list=""
for i in ${action_list}
do
    case $i in
        temp)
            label=$(translate_label "${_HWSUPP_TEMP}")
        ;;
        hwmon)
            label=$(translate_label "${_HWSUPP_HWMON}")
        ;;
    esac
    if [ "$FORM_action" = "raspberry_pi_$i" ]
    then
        tab_list=`echo "$tab_list $label no"`
    else
        tab_list=`echo "$tab_list $label $myname?action=raspberry_pi_$i"`
    fi
done

show_tab_header $tab_list
case $FORM_action in
    raspberry_pi_hwmon)
        hwmon_raspberry_pi
    ;;
    *)
        rrd_open_tab_list $FORM_action
        rrd_render_graph $FORM_action
        rrd_close_tab_list
    ;;
esac

show_tab_footer

show_html_footer

# _oOo_
