CAPIINIT_VERSION = $(ISDNUTILS_VERSION)
CAPIINIT_SOURCE = $(ISDNUTILS_SOURCE)
CAPIINIT_PATCH = $(ISDNUTILS_PATCH)
CAPIINIT_SITE = $(ISDNUTILS_SITE)
CAPIINIT_SUBDIR = capiinit

CAPIINIT_LICENSE = GPLv2+
CAPIINIT_LICENSE_FILES = gpl-2.0.txt

CAPIINIT_CONF_ENV = $(ISDNUTILS_CONF_ENV)
CAPIINIT_MAKE_OPTS = CFLAGS="$(TARGET_CFLAGS)"

CAPIINIT_PRE_CONFIGURE_HOOKS += ISDNUTILS_PREPARE_CONFIG

define CAPIINIT_TOUCH_MAKEFILE
	touch $(@D)/$(CAPIINIT_SUBDIR)/Makefile.in
endef
CAPIINIT_PRE_CONFIGURE_HOOKS += CAPIINIT_TOUCH_MAKEFILE

define CAPIINIT_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/$(CAPIINIT_SUBDIR)/capiinit $(TARGET_DIR)/sbin/capiinit
endef

$(eval $(call autotools-package))
