ISDNCTRL_VERSION = $(ISDNUTILS_VERSION)
ISDNCTRL_SOURCE = $(ISDNUTILS_SOURCE)
ISDNCTRL_PATCH = $(ISDNUTILS_PATCH)
ISDNCTRL_SITE = $(ISDNUTILS_SITE)
ISDNCTRL_SUBDIR = isdnctrl

ISDNCTRL_LICENSE = GPLv2+
ISDNCTRL_LICENSE_FILES= gpl-2.0.txt

ISDNCTRL_DEPENDENCIES = libisdn
ISDNCTRL_CONF_ENV = $(ISDNUTILS_CONF_ENV)
ISDNCTRL_MAKE_OPTS = CFLAGS="$(TARGET_CFLAGS)"

ISDNCTRL_PRE_CONFIGURE_HOOKS += ISDNUTILS_PREPARE_CONFIG

define ISDNCTRL_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/$(ISDNCTRL_SUBDIR)/isdnctrl $(TARGET_DIR)/sbin/isdnctrl
endef

$(eval $(call autotools-package))
