LIBISDN_VERSION = $(ISDNUTILS_VERSION)
LIBISDN_SOURCE = $(ISDNUTILS_SOURCE)
LIBISDN_PATCH = $(ISDNUTILS_PATCH)
LIBISDN_SITE = $(ISDNUTILS_SITE)
LIBISDN_SUBDIR  := lib

LIBISDN_LICENSE = GPLv2+
LIBISDN_LICENSE_FILES = gpl-2.0.txt

LIBISDN_CONF_ENV = $(ISDNUTILS_CONF_ENV)
LIBISDN_INSTALL_STAGING = YES

LIBISDN_PRE_CONFIGURE_HOOKS += ISDNUTILS_PREPARE_CONFIG

define LIBISDN_CONFIGURE_CMDS
	+$(MAKE) CC=$(TARGET_CC) LD=$(TARGET_LD) CFLAGS="$(TARGET_CFLAGS)" \
		-C $(@D)/$(LIBISDN_SUBDIR) -f Makefile.in config
endef

define LIBISDN_BUILD_CMDS
	+$(MAKE) CC=$(TARGET_CC) LD=$(TARGET_LD) CFLAGS="$(TARGET_CFLAGS)" \
		-C $(@D)/$(LIBISDN_SUBDIR) -f Makefile.in
endef

define LIBISDN_INSTALL_STAGING_CMDS
	$(INSTALL) -D $(@D)/$(LIBISDN_SUBDIR)/libisdn.a $(STAGING_DIR)/usr/lib/libisdn.a
endef

$(eval $(call generic-package))
