IPPPD_VERSION = $(ISDNUTILS_VERSION)
IPPPD_SOURCE = $(ISDNUTILS_SOURCE)
IPPPD_PATCH = $(ISDNUTILS_PATCH)
IPPPD_SITE = $(ISDNUTILS_SITE)
IPPPD_SUBDIR = ipppd

IPPPD_LICENSE = GPLv2+
IPPPD_LICENSE_FILES = gpl-2.0.txt

IPPPD_DEPENDENCIES = libpcap host-autoconf

IPPPD_CONF_ENV = $(ISDNUTILS_CONF_ENV)
IPPPD_CONF_OPTS = --enable-ippp-filter --enable-mschap
IPPPD_MAKE_OPTS = CFLAGS="$(TARGET_CFLAGS) -DREQ_SYSOPTIONS=0"

IPPPD_PRE_CONFIGURE_HOOKS += ISDNUTILS_PREPARE_CONFIG

define IPPPD_AUTOCONF
	cd $(@D)/ipppd; $(HOST_MAKE_ENV) autoconf
endef
IPPPD_PRE_CONFIGURE_HOOKS += IPPPD_AUTOCONF

define IPPPD_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/$(IPPPD_SUBDIR)/ipppd $(TARGET_DIR)/sbin/ipppd
endef

$(eval $(call autotools-package))
