AVMCAPICTRL_VERSION = $(ISDNUTILS_VERSION)
AVMCAPICTRL_SOURCE = $(ISDNUTILS_SOURCE)
AVMCAPICTRL_PATCH = $(ISDNUTILS_PATCH)
AVMCAPICTRL_SITE = $(ISDNUTILS_SITE)
AVMCAPICTRL_SUBDIR = avmb1

AVMCAPICTRL_LICENSE = GPLv2+
AVMCAPICTRL_LICENSE_FILES = gpl-2.0.txt

AVMCAPICTRL_CONF_ENV = $(ISDNUTILS_CONF_ENV)
AVMCAPICTRL_MAKE_OPTS = CFLAGS="$(TARGET_CFLAGS)"

AVMCAPICTRL_PRE_CONFIGURE_HOOKS += ISDNUTILS_PREPARE_CONFIG

define AVMCAPICTRL_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/$(AVMCAPICTRL_SUBDIR)/avmcapictrl $(TARGET_DIR)/sbin/avmcapictrl
endef

$(eval $(call autotools-package))
