ICNCTRL_VERSION = $(ISDNUTILS_VERSION)
ICNCTRL_SOURCE = $(ISDNUTILS_SOURCE)
ICNCTRL_PATCH = $(ISDNUTILS_PATCH)
ICNCTRL_SITE = $(ISDNUTILS_SITE)
ICNCTRL_SUBDIR = icn

ICNCTRL_LICENSE = GPLv2+
ICNCTRL_LICENSE_FILES = gpl-2.0.txt

ICNCTRL_CONF_ENV = $(ISDNUTILS_CONF_ENV)
ICNCTRL_MAKE_OPTS = CFLAGS="$(TARGET_CFLAGS)"

ICNCTRL_PRE_CONFIGURE_HOOKS += ISDNUTILS_PREPARE_CONFIG

define ICNCTRL_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/$(ICNCTRL_SUBDIR)/icnctrl $(TARGET_DIR)/sbin/icnctrl
endef

$(eval $(call autotools-package))
